version: '3.8'
services:
  backend:
    image: pneumonia-backend:v1
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models  # Mount the models directory if needed
    networks:
      - pneumonia-network

  frontend:
    image: pneumonia-frontend:v1
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Backend URL for frontend
    depends_on:
      - backend
    networks:
      - pneumonia-network

networks:
  pneumonia-network:
    driver: bridge