apiVersion: v1
kind: Service
metadata:
  name: pneumonia-frontend-service
  labels:
    app: pneumonia-frontend
spec:
  selector:
    app: pneumonia-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
  type: NodePort