apiVersion: apps/v1
kind: Deployment
metadata:
  name: pneumonia-frontend
  labels:
    app: pneumonia-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pneumonia-frontend
  template:
    metadata:
      labels:
        app: pneumonia-frontend
    spec:
      containers:
      - name: pneumonia-frontend
        image: pneumonia-frontend:v2
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"